Enhanced cdproj with more validity checks, and is now based on mew concept: a project is one with a git repository.

diff --git a/packages/scripts/functions/cdproj b/packages/scripts/functions/cdproj
--- a/packages/scripts/functions/cdproj
+++ b/packages/scripts/functions/cdproj
@@ -11,10 +11,31 @@
 
 cdproj ()
 {
-	cd ~/projects/${1}
-	
-	if [[ -d .git ]]
+	local repoUser
+
+	if [[ -d ${1} ]]
 	then
-		gitInit $(gitGetRepoUser)
+		if [[ -d ${1}/.git ]]
+		then
+			cd ~/projects/${1}
+
+			if repoUser=$(gitGetRepoUser)
+			then
+				if ! gitInit ${repoUser}
+				then
+					echo "Could not find credentials for the git service for the specified project" >&2
+					return 1
+				fi
+			else
+				echo "The git user account cannot be found or is not valid." >&2
+				return 1
+			fi
+		else
+			echo "The specified project is not a git repository." >&2
+			return 1
+		fi
+	else
+		echo "The specified project directory does not exist." >&2
+		return 1
 	fi
 }
