Added default CSS generation

diff --git a/packages/swdev/adoc/scripts/adocRunOnSave b/packages/swdev/adoc/scripts/adocRunOnSave
--- a/packages/swdev/adoc/scripts/adocRunOnSave
+++ b/packages/swdev/adoc/scripts/adocRunOnSave
@@ -8,7 +8,78 @@
 #	
 #_doc ${1} 20240810112648 " " && exit 0
 
-basename="${1}"
+basename="${1%.adoc}"
+
+if [[ ! -f "${basename}.adoc" ]]
+then
+	echo >&2 "Cannot find ${basename}.adoc"
+	exit 1
+fi
+
+if [[ ! -f "${basename}.css" ]]
+then
+	echo >&2 "Cannot find ${basename}.css, generating a default version of the CSS file."
+	cat <<EOF > ${basename}.css
+@page {
+    margin: 1.5cm 1.5cm 1.5cm 1.5cm;
+  }
+  
+body {
+  font-family: 'Fira Sans', sans-serif;
+  -webkit-font-smoothing: antialiased;
+  text-rendering: optimizeSpeed;
+  font-size: 10pt;
+  text-align: left;
+  height: 29.7cm;
+  width: 21cm;
+  margin: 0;
+  display: flex;
+  flex-direction: column;
+}
+ 
+h1, h2, h3, h4, h5 {
+  font-family: 'Fira Sans', sans-serif;
+  -webkit-font-smoothing: antialiased;
+  text-rendering: optimizeLegibility;
+}
+
+h1 {
+  font-size: 22pt;
+}
+
+h2 {
+  font-size: 16pt; 
+}
+
+h3 {
+  font-size: 14pt;
+}
+
+h4 {
+  font-size: 12pt;
+}
+
+h5 {
+  font-size: 10pt;
+}
+
+ul {
+  padding-inline-start: 12pt;
+}
+
+li p {
+  margin-top: 6pt;
+  margin-bottom: 0pt;
+}
+
+
+/* h3 + 
+:contains("Earlier")  {
+  color: blue;
+} */
+
+EOF
+fi
 
 adocHtmlPdfCmd="/tmp/asciidoctor-web-pdf-linux-v1.0.0-alpha.16/asciidoctor-web-pdf"
 adocHtmlCmd="asciidoctor"
@@ -16,11 +87,13 @@ adocHtmlCmd="asciidoctor"
 adocHtmlPdfOpts="-a stylesheet -a stylesheet=${basename}.css"
 adocHtmlOpts="-a stylesheet -a stylesheet=${basename}.css"
 
-${adocHtmlPdfCmd} ${adocHtmlPdfOpts} ${basename}.adoc
-${adocHtmlCmd} ${adocHtmlOpts} ${basename}.adoc
+while (inotifywait -e modify ${basename}.adoc ${basename}.css)
+do
+    ${adocHtmlPdfCmd} ${adocHtmlPdfOpts} ${basename}.adoc
+    ${adocHtmlCmd} ${adocHtmlOpts} ${basename}.adoc
 
-mv ${basename}.pdf /local/xfer
-mv ${basename}.html /local/xfer
+    mv ${basename}.pdf /local/xfer
+    mv ${basename}.html /local/xfer
 
-[[ -f diag-plantuml ]] && rm diag-plantuml
-
+    [[ -f diag-plantuml ]] && rm diag-plantuml
+done
